# Generated by Django 4.2.28 on 2026-02-25 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Olympiad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("online", "Онлайн"),
                            ("offline", "Офлайн"),
                            ("hybrid", "Гибридный"),
                        ],
                        default="online",
                        max_length=20,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("school", "Школьный"),
                            ("regional", "Региональный"),
                            ("national", "Всероссийский"),
                            ("international", "Международный"),
                        ],
                        max_length=20,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "organizer_url",
                    models.URLField(blank=True, verbose_name="Сайт организатора"),
                ),
                (
                    "min_grade",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Минимальный класс"
                    ),
                ),
                (
                    "max_grade",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Максимальный класс"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликована"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата создания"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="olympiads",
                        to="subjects.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Олимпиада",
                "verbose_name_plural": "Олимпиады",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OlympiadStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название этапа"),
                ),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("qualifying", "Отборочный"),
                            ("semifinal", "Полуфинал"),
                            ("final", "Финал"),
                        ],
                        max_length=20,
                        verbose_name="Тип этапа",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Дата начала")),
                ("end_date", models.DateTimeField(verbose_name="Дата окончания")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "olympiad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="olympiads.olympiad",
                        verbose_name="Олимпиада",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап олимпиады",
                "verbose_name_plural": "Этапы олимпиад",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="OlympiadRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Зарегистрирован"),
                            ("participated", "Участвовал"),
                            ("winner", "Призёр"),
                            ("disqualified", "Дисквалифицирован"),
                        ],
                        default="registered",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата регистрации",
                    ),
                ),
                (
                    "result_score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Результат"
                    ),
                ),
                (
                    "olympiad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="olympiads.olympiad",
                        verbose_name="Олимпиада",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="olympiad_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регистрация на олимпиаду",
                "verbose_name_plural": "Регистрации на олимпиады",
                "unique_together": {("user", "olympiad")},
            },
        ),
    ]
