# Generated by Django 4.2.28 on 2026-03-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olympiads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="olympiad",
            name="regulations_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="olympiads/regulations/",
                verbose_name="Положение об олимпиаде",
            ),
        ),
    ]
